name: team_tasker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  lottie: ^3.1.2
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/animation/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNovaFont.otf
